version: "3.8"

services:

  employee-mysql:
    image: mysql:8
    container_name: employee-mysql
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10


  employee-app:
    image: employee-management:v1
    container_name: employee-app
    ports:
      - "8080:8080"
    depends_on:
      employee-mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://employee-mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


volumes:
  mysql-data: